[build]
  command = "npm run build"

  publish = ".output/public"

[build.environment]
  NITRO_PRESET = "static"
  NODE_VERSION = "20"


  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
